"""
Django settings for todoapp project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

from decouple import config # pour utiliser la bibliothèque python-decouple pour gérer les variables d'environnement

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')
# pour le développement local, on peut utiliser une clé secrète simple.
# En production, il faudra générer une clé secrète plus complexe et la garder secrète pour des raisons de sécurité.
# On peut utiliser la commande `python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"` pour générer une clé secrète aléatoire.
# Il est important de ne pas partager la clé secrète en public, car elle est utilisée pour sécuriser les sessions, les cookies et d'autres fonctionnalités de sécurité de Django. En production, il est recommandé de stocker la clé secrète dans une variable d'environnement ou dans un fichier de configuration séparé qui n'est pas inclus dans le contrôle de version (par exemple, en utilisant un fichier .env avec la bibliothèque python-decouple).

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False) # pour le développement local, on peut laisser le mode debug activé. En production, il faudra le désactiver pour des raisons de sécurité.

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default=[]).split(',') # pour le développement local, on peut laisser la liste des hôtes autorisés vide. En production, il faudra ajouter les domaines autorisés à accéder à l'application.


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'todolist', # notre application de gestion de tâches, # pour utiliser le style Bootstrap 5 avec Crispy Forms
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'todoapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR, "templates"], # pour indiquer à Django où se trouvent les templates de notre projet
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'todoapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DATABASE_NAME'),
        'USER': config('USER'),
        'PASSWORD': config('PASSWORD'),
        'HOST': config('HOST'),
        'PORT': config('PORT'),
    }
} # configuration de la base de données PostgreSQL pour notre projet Django


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
] # pour indiquer à Django où se trouvent les fichiers statiques de notre projet (par exemple, les fichiers CSS, JavaScript et les images que nous avons créés pour notre application). En développement, on peut laisser cette variable vide ou la configurer pour qu'elle pointe vers un répertoire temporaire. En production, il faudra utiliser la commande `collectstatic` pour collecter tous les fichiers statiques dans un répertoire spécifique (par exemple, `staticfiles`) et configurer la variable `STATICFILES_ROOT` pour indiquer à Django où se trouvent ces fichiers collectés.

STATIC_ROOT = BASE_DIR / "staticfiles"  # pour indiquer à Django où se trouvent les fichiers statiques collectés par la commande `collectstatic` en production. En développement, on peut laisser cette variable vide ou la configurer pour qu'elle pointe vers un répertoire temporaire.




# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
