# Generated by Django 5.2.12 on 2026-04-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_alter_tache_description_alter_tache_titre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tache',
            name='terminee',
        ),
        migrations.AddField(
            model_name='tache',
            name='status',
            field=models.CharField(choices=[('En cours', 'En cours'), ('Annulée', 'Annulée'), ('Terminée', 'Terminée')], default='En cours', max_length=20),
        ),
    ]
